extends Node

# ===================== LOBBY CONTROLLS =====================
# Manages the lobby UI, works with the LobbyManager to manage the players
# Really need to update the UI, it's a bit of a mess
# =============================================================

var sub_menu: Control = null
var settings_menu: Control = null
var game_list: Control = null
var menu: Variant = null
var menu2: Variant = null
var used_ip: String = NetworkConst.DEFAULT_SERVER_IP
var used_port: int = 8080
var used_lobby_name = "Default"
var game_started = false

const CONNECTION_TIMEOUT = 5.0

# Example structure of ONE element inside the current_game_list Array:
#{
#    "id": "192.168.1.100:7777", # String: Unique ID generated by server (ip:port)
#    "name": "Player One's Game", # String: Name provided by the host
#    "ip": "192.168.1.100",      # String: Public IP address of the host
#    "port": 7777,                 # Int: Port the host is listening on for P2P
#    "players": 2,                 # Int: Current number of players (including host)
#    "maxPlayers": 4,              # Int: Maximum players allowed
#    "gameVersion": "1.0",         # String: Version info from host (optional)
#    "gameMode": "Standard"        # String: Game mode info from host (optional)
#}

# ===================== CORE FUNCTIONS =====================
func _ready() -> void:
	menu2 = Settings.get_ui_instance("Menu")
	add_child(menu2)
	menu = menu2.get_child(0)
	sub_menu =	menu.get_node("Sub Menu")
	settings_menu = menu.get_node("Settings Sub Menu")
	Net.player_connected.connect(set_player_names)
	Net.player_connection_failed.connect(connection_failed)
	menu.get_node("Menu").get_node("Host").pressed.connect(open_host_game)
	menu.get_node("Menu").get_node("Join").pressed.connect(open_join_game)
	menu.get_node("Menu").get_node("Exit").pressed.connect(exit_game)
	menu.get_node("Menu").get_node("Tools").pressed.connect(open_tools)
	menu.get_node("Menu").get_node("Settings").pressed.connect(open_settings)
	menu.get_node("Menu").get_node("Version").text = "Version: " + GameConst.GAME_VERSION
	sub_menu.get_node("Lobby Name").get_node("Input").text_changed.connect(func(): used_lobby_name = sub_menu.get_node("Lobby Name").get_node("Input").text)
	sub_menu.get_node("Start Button").pressed.connect(start_game)
	sub_menu.get_node("Upload").pressed.connect(upload_maps)
	game_list = menu.get_node("GameList").get_node("List")
	game_list.get_child(0).pressed.connect(Net.refresh_game_list)
	game_list.get_child(1).item_selected.connect(func(index): used_ip = game_list.get_child(1).get_item_metadata(index)["ip"]; used_port = game_list.get_child(1).get_item_metadata(index)["port"])
	menu.get_node("GameList").get_node("Button2").pressed.connect(func(): join_game(used_ip, used_port))
	Net.game_list_updated.connect(update_game_list)
	Settings.prologue_map = ExternalUtility.get_first_file_in_dir("user://Assets/Maps").replace(".dd2vtt", "")
	#Settings._on_first_startup()
	Settings.load_settings()
	Settings.apply_settings()
	add_prologue_options()

func _process(_delta):
	if !game_started:
		if Net.get_player_count() >= 1 and Net.is_host() and ExternalUtility.get_all_files_in_dir("user://Assets/Maps").size() > 0:
			enable_start_game()
		else:
			disable_start_game()

func _input(event):
	if event is InputEventKey:
		if Input.is_action_just_pressed("PAUSE"):
			if get_node("GameUI").get_node("Pause").visible:
				close_pause_menu()
			else:
				open_pause_menu()

# ===================== HELPER FUNCTIONS =====================
# Open the host game menu
# Args: None
# Returns: None
func open_host_game() -> void:
	print("Open Host Game")
	if sub_menu.container_name == "Host Game" and sub_menu.visible:
		sub_menu.visible = false
		return

	sub_menu.visible = true
	settings_menu.visible = false
	sub_menu.container_name = "Host Game"
	menu.get_node("Menu").get_node("Join").button_pressed = false
	menu.get_node("Menu").get_node("Tools").button_pressed = false
	menu.get_node("Menu").get_node("Settings").button_pressed = false
	sub_menu.get_node("Menu Name").text = "HOST GAME"
	sub_menu.get_node("Button").text = "HOST"

	for control in sub_menu.get_children():
		control.visible = false

	for control in get_tree().get_nodes_in_group("Join"):
		control.visible = false

	for control in get_tree().get_nodes_in_group("Host"):
		control.visible = true

	if sub_menu.get_node("Button").pressed.is_connected(join_game):
		sub_menu.get_node("Button").pressed.disconnect(join_game)

	if sub_menu.get_node("Button").pressed.is_connected(host_game):
		return
	sub_menu.get_node("Button").pressed.connect(host_game)

# Open the join game menu
# Args: None
# Returns: None
func open_join_game() -> void:
	if sub_menu.container_name == "Join Game" and sub_menu.visible:
		sub_menu.visible = false
		return

	sub_menu.visible = true
	settings_menu.visible = false
	sub_menu.container_name = "Join Game"
	menu.get_node("Menu").get_node("Host").button_pressed = false
	menu.get_node("Menu").get_node("Tools").button_pressed = false
	menu.get_node("Menu").get_node("Settings").button_pressed = false
	sub_menu.get_node("Menu Name").text = "JOIN GAME"
	sub_menu.get_node("Button").text = "OPEN"

	for control in sub_menu.get_children():
		control.visible = false
	
	for control in get_tree().get_nodes_in_group("Host"):
		control.visible = false

	for control in get_tree().get_nodes_in_group("Join"):
		control.visible = true

	if sub_menu.get_node("Button").pressed.is_connected(host_game):
		sub_menu.get_node("Button").pressed.disconnect(host_game)

	if sub_menu.get_node("Button").pressed.is_connected(open_game_list):
		return
	sub_menu.get_node("Button").pressed.connect(open_game_list)

func open_tools() -> void:
	if sub_menu.container_name == "Tools" and sub_menu.visible:
		sub_menu.visible = false
		return

	sub_menu.visible = true
	settings_menu.visible = false
	sub_menu.container_name = "Tools"
	menu.get_node("Menu").get_node("Host").button_pressed = false
	menu.get_node("Menu").get_node("Join").button_pressed = false
	menu.get_node("Menu").get_node("Settings").button_pressed = false
	sub_menu.get_node("Menu Name").text = "TOOLS"

	for control in sub_menu.get_children():
		control.visible = false

	for control in get_tree().get_nodes_in_group("Tools"):
		control.visible = true
	
	sub_menu.get_node("Menu Name").visible = true

	if sub_menu.get_node("Button").pressed.is_connected(open_tools):
		return
	sub_menu.get_node("Button").pressed.connect(open_tools)

func open_settings() -> void:
	if settings_menu.visible:
		settings_menu.visible = false
		return

	settings_menu.visible = true
	sub_menu.visible = false
	menu.get_node("Menu").get_node("Host").button_pressed = false
	menu.get_node("Menu").get_node("Join").button_pressed = false
	menu.get_node("Menu").get_node("Tools").button_pressed = false
	
	var audio = settings_menu.get_node("Audio")
	var video = settings_menu.get_node("Video")

	audio.get_node("Master Volume").get_node("Slider").value = Settings.audio_settings["master_volume"]
	audio.get_node("Music Volume").get_node("Slider").value = Settings.audio_settings["music_volume"]
	audio.get_node("SFX Volume").get_node("Slider").value = Settings.audio_settings["sfx_volume"]
	audio.get_node("UI Volume").get_node("Slider").value = Settings.audio_settings["menu_sfx_volume"]
	video.get_node("Resolution").get_node("Options").selected = SettingConst.RESOLUTIONS.find(Vector2i(Settings.window_settings["resolution"]))
	video.get_node("Display Mode").get_node("Options").selected = Settings.window_settings["display_mode"]

	if !audio.get_node("Master Volume").get_node("Slider").value_changed.is_connected(Settings.set_master_volume):
		audio.get_node("Master Volume").get_node("Slider").value_changed.connect(Settings.set_master_volume)
	if !audio.get_node("Music Volume").get_node("Slider").value_changed.is_connected(Settings.set_music_volume):
		audio.get_node("Music Volume").get_node("Slider").value_changed.connect(Settings.set_music_volume)
	if !audio.get_node("SFX Volume").get_node("Slider").value_changed.is_connected(Settings.set_sfx_volume):
		audio.get_node("SFX Volume").get_node("Slider").value_changed.connect(Settings.set_sfx_volume)
	if !audio.get_node("UI Volume").get_node("Slider").value_changed.is_connected(Settings.set_menu_sfx_volume):
		audio.get_node("UI Volume").get_node("Slider").value_changed.connect(Settings.set_menu_sfx_volume)
	if !video.get_node("Resolution").get_node("Options").item_selected.is_connected(Settings.set_resolution):
		video.get_node("Resolution").get_node("Options").item_selected.connect(Settings.set_resolution)
	if !video.get_node("Display Mode").get_node("Options").item_selected.is_connected(Settings.set_display_mode):
		video.get_node("Display Mode").get_node("Options").item_selected.connect(Settings.set_display_mode)
		

# Open the join game menu
# Args: None
# Returns: None
func host_game() -> void:
	set_peer_name(sub_menu.get_node("Peer Name").get_node("Input").text)
	Net.create_game(used_lobby_name, 4, GameConst.GAME_VERSION)
	set_button_state(false)

# Open the join game menu
# Args: None
# Returns: None
func join_game(ip, port) -> void:
	set_peer_name(sub_menu.get_node("Peer Name").get_node("Input").text)
	Net.join_game(ip, port)
	set_loading(true)
	set_button_state(false)

# Connection to server failed so reset the button state
# Args: None
# Returns: None
func connection_failed() -> void:
	print("Connection failed")
	set_loading(false)
	set_button_state(true)

# Start the game
# Args: None
# Returns: None
func start_game() -> void:
	Net.load_game("res://Scenes/Game.tscn", self)
	game_started = true

func update_game_list(new_game_list) -> void:
	var list = game_list.get_child(1)
	list.clear()
	for game in new_game_list:
		var game_name = game["name"]
		var players_str = "%d/%d" % [int(game.get("players", 0)), int(game.get("maxPlayers", 0))]
		var game_version = game.get("gameVersion", "Unknown")
		list.add_item(game_name + "-" + players_str + "-" + game_version, null, true)
		game["ip"] = game["ip"].replace("::ffff:", "")
		list.set_item_metadata(list.get_item_count() - 1, game)

func open_game_list() -> void:
	Net.refresh_game_list()
	game_list.get_parent().visible = true

# Exit the game
# Args: None
# Returns: None
func exit_game() -> void:
	if Net.is_host():
		for saves in get_tree().get_nodes_in_group("Savable"):
			saves._save()

	var map = get_tree().get_first_node_in_group("Map")
	if map:
		map.save_map_file()

	if multiplayer.multiplayer_peer:
		if Net.is_host():
			await Cache.upload(self, false)
	print_orphan_nodes()
	get_tree().quit()

func upload_maps() -> void:
	set_loading(true)
	get_node("Cache").upload(sub_menu.get_node("Loading"))

# Enable the start game button
# Args: None
# Returns: None
func enable_start_game() -> void:
	sub_menu.get_node("Start Button").disabled = false

# Disable the start game button
# Args: None
# Returns: None
func disable_start_game() -> void:
	sub_menu.get_node("Start Button").disabled = true

# Set the player names
# Args: Array - The player names
# Returns: None
func set_player_names(_player_id: int, _player_info: Dictionary) -> void:
	print(multiplayer.get_unique_id())
	menu.get_node("GameList").visible = false
	menu.get_node("GameLobby").visible = true
	var player_names = ""
	for player in Net.get_player_names(): player_names += player + "\n"
	menu.get_node("GameLobby").get_node("Info").text = Net.get_host_name()
	menu.get_node("GameLobby").get_node("player_info").text = "[center]" + player_names + "[/center]"
	set_loading(false)

# Set the peer name
# Args: String - The peer name
# Returns: None
func set_peer_name(peer_name: String) -> void:
	Net.player_info["name"] = peer_name

# Set the loading state
# Args: bool - The loading state
# Returns: None
func set_loading(loading: bool) -> void:
	sub_menu.get_node("Loading").visible = loading

# Set the button state
# Args: bool - The button state
# Returns: None
func set_button_state(state: bool) -> void:
	sub_menu.get_node("Button").disabled = !state

# Set the prologue map/starting map for the game
# Args: int - The index of the map
# Returns: None
func set_prologue_map(index: int) -> void:
	Settings.prologue_map = sub_menu.get_node("StartingMap").get_node("Maps").get_item_text(index)
	Settings.prologue_index = index

# Set the GM player state, if they chose to be a player or not
# Args: bool - The GM player state
# Returns: None
func set_gm_player_state(enabled: bool) -> void:
	Settings.is_player = enabled

func set_host_state(enabled: bool) -> void:
	if enabled:
		used_ip = NetworkConst.LOCAL_SERVER_IP
	else:
		used_ip = NetworkConst.DEFAULT_SERVER_IP

func open_pause_menu() -> void:
	if Bus.pause_busy:
		print("Pause state:", Bus.pause_busy)
		return
	get_node("GameUI").get_node("Pause").visible = true

func close_pause_menu() -> void:
	get_node("GameUI").get_node("Pause").visible = false

# Add the prologue options
# Args: None
# Returns: None
func add_prologue_options() -> void:
	sub_menu.get_node("StartingMap").get_node("Maps").clear()

	var maps_folder_path = "user://Assets/Maps"
	var map_names = ExternalUtility.get_all_files_in_dir(maps_folder_path, true)
	Settings.prologue_map = map_names[0].replace(".dd2vtt", "")
	for map_name in map_names:
		if ExternalUtility.check_dd2vtt_image_dimensions(maps_folder_path + "/" + map_name) > SettingConst.MAX_MAP_SIZE:
			print("Map: ", map_name, " is too large, skipping.")
			continue
		var clean_map_name = map_name.replace(".dd2vtt", "")
		sub_menu.get_node("StartingMap").get_node("Maps").add_item(clean_map_name)

	if sub_menu.get_node("StartingMap").get_node("Maps").item_selected.is_connected(set_prologue_map):
		return
	sub_menu.get_node("StartingMap").get_node("Maps").item_selected.connect(set_prologue_map)
